name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install Dependencies
      run: |
          cd ./projectnumer
          npm ci
          cd ./server
          npm ci
    - name: Test Frontend
      run: |
          cd ./projectnumer
          npm test
    - name: Test Backend
      run: |
          cd ./server
          npm test
    - name: Build Docker Image
      run: docker-compose build
